var json = {
	"course1": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "RiverFront"],
		"location": ["Location:", "Roseburg Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-6-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "Yes"],
		"courseRating": ["Course Rating:", "8"],
		"comments": ["Comments:", "Neat Course"],
	},
	"course2": {
		"select": ["Par:", "Par4"],
		"cname": ["Course Name:", "Whistlers bend"],
		"location": ["Location:", "Roseburg Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-6-10"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "Yes"],
		"courseRating": ["Course Rating:", "10"],
		"comments": ["Comments:", "Awesome Course"],
	},
	"course3": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Lawsons Bar"],
		"location": ["Location:", "Myrtle Creek Oregon"],
		"totalholes": ["Total Holes:", "9"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-7-4"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "2"],
		"comments": ["Comments:", "Not very good"],
	},
	"course4": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Cottage Grove"],
		"location": ["Location:", "Cottage Grove Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-5-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "7"],
		"comments": ["Comments:", "Very good"],
	},
	"course5": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "Pass Creek Park"],
		"location": ["Location:", "Drain Oregon"],
		"totalholes": ["Total Holes:", "9"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2010-7-4"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "5"],
		"comments": ["Comments:", "New Course"],
	},
	"course6": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "Dexter"],
		"location": ["Location:", "Dexter Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-4-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "8"],
		"comments": ["Comments:", "Pretty awesome course."],
	},
	"course7": {
		"select": ["Par:", "Par4"],
		"cname": ["Course Name:", "Whispering Pines"],
		"location": ["Location:", "Portland Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2000-7-4"],
		"targets": ["Target Type:", "Mixed"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "5"],
		"comments": ["Comments:", "Decent Course"],
	},
	"course8": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Lake Selmac"],
		"location": ["Location:", "Selma Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2009-7-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "5"],
		"comments": ["Comments:", "Awesome course around a lake"],
	},
	"course9": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "Walkabout Creek"],
		"location": ["Location:", "The northern territory"],
		"totalholes": ["Total Holes:", "27"],
		"rname": ["Reviewer Name:", "Paul Hogan"],
		"reviewdate": ["Review Date:", "2008-7-4"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "5"],
		"comments": ["Comments:", "Not very good"],
	},
	"course10": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Beaver Mill"],
		"location": ["Location:", "Somewhere Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-7-4"],
		"targets": ["Target Type:", "Mixed"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "4"],
		"comments": ["Comments:", "Not very good"],
	},
	"course11": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Example Course"],
		"location": ["Location:", "Roseburg Oregon"],
		"totalholes": ["Total Holes:", "14"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2001-7-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "2"],
		"comments": ["Comments:", "Not very good"],
	},
	"course12": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Aspen Lake"],
		"location": ["Location:", "Eugene Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2001-7-4"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "5"],
		"comments": ["Comments:", "Not bad"],
	},
	"course13": {
		"select": ["Par:", "Par4"],
		"cname": ["Course Name:", "Shamus Valley"],
		"location": ["Location:", "Coos Bay Oregon"],
		"totalholes": ["Total Holes:", "9"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-7-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "6"],
		"comments": ["Comments:", "Nice Oregon coast course."],
	},
	"course14": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "Maple Mill"],
		"location": ["Location:", "Rice Hill Oregon"],
		"totalholes": ["Total Holes:", "9"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-7-4"],
		"targets": ["Target Type:", "Mixed"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "2"],
		"comments": ["Comments:", "Not very good"],
	},
	"course15": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "Pine Ridge"],
		"location": ["Location:", "Medford Oregon"],
		"totalholes": ["Total Holes:", "18"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2005-6-4"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "4"],
		"comments": ["Comments:", "Decent 18 hole course."],
	},
	"course16": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Winchester Ridge"],
		"location": ["Location:", "Winchester Oregon"],
		"totalholes": ["Total Holes:", "9"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-1-6"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "3"],
		"comments": ["Comments:", "Eh..."],
	},
	"course17": {
		"select": ["Par:", "Par4"],
		"cname": ["Course Name:", "Swiftwater Creek"],
		"location": ["Location:", "Beaverton Oregon"],
		"totalholes": ["Total Holes:", "27"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2002-7-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "9"],
		"comments": ["Comments:", "Championship level course."],
	},
	"course18": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Beaversdale Greens"],
		"location": ["Location:", "Tigard Oregon"],
		"totalholes": ["Total Holes:", "27"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2007-4-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "Yes"],
		"courseRating": ["Course Rating:", "9"],
		"comments": ["Comments:", "The stuff dreams are made of."],
	},
	"course19": {
		"select": ["Par:", "Par5"],
		"cname": ["Course Name:", "Heavens gate"],
		"location": ["Location:", "Canby Oregon"],
		"totalholes": ["Total Holes:", "27"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-7-4"],
		"targets": ["Target Type:", "Baskets"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "10"],
		"comments": ["Comments:", "Tournament Course"],
	},
	"course20": {
		"select": ["Par:", "Par3"],
		"cname": ["Course Name:", "Maple Bar"],
		"location": ["Location:", "Myrtle Creek Oregon"],
		"totalholes": ["Total Holes:", "9"],
		"rname": ["Reviewer Name:", "Nathan Baker"],
		"reviewdate": ["Review Date:", "2011-7-4"],
		"targets": ["Target Type:", "Tones"],
		"favorite": ["Favorite:", "No"],
		"courseRating": ["Course Rating:", "2"],
		"comments": ["Comments:", "Not very good"],
	}
}